### ISSUE TITLE
MI - PERFORMANCE TUNING (HTTP transport)

### ISSUE THREAD

**Issue by nilminiwso2** [wso2/docs-ei#150]
Complete docs on tuning the HTTP transport [1].

[1] https://github.com/wso2/docs-ei/blob/master/en/micro-integrator/docs/setup/performance_tuning/http_transport_tuning.md

**Comment by nilminiwso2** [comment]
For the blocking scenario of [1], the following xml config is given:
```
<transportsender class="org.apache.axis2.transport.http.CommonsHTTPTransportSender" name="http">
            <parameter name="PROTOCOL">HTTP/1.1</parameter>
            <parameter name="Transfer-Encoding">chunked</parameter>
            <parameter name="cacheHttpClient">true</parameter>
            <parameter name="defaultMaxConnectionsPerHost">100</parameter>
    </transportsender>
```
The above was replaced by the following toml. @madushadhanushka - kindly confirm.
```toml
[transport.http]
blocking_sender.enable_client_caching = true
blocking_sender.transfer_encoding = "chunked"
blocking_sender.default_connections_per_host = 100
```
