### ISSUE TITLE
IBM WebSphere MQ configurations should be updated to TOML format

### ISSUE THREAD

**Issue by madushadhanushka** [wso2/docs-ei#895]
**Description:**
Example given in the [IBM WebSphereMQ doc](https://ei.docs.wso2.com/en/latest/micro-integrator/setup/brokers/configure-with-IBM-websphereMQ/) still in previous configuration format. This should be updated with new TOML config model.

**Comment by madushadhanushka** [comment]
Configurations should be changed as follows
Queue Scenario 1: Client to Queue to WSO2 EI
1.
```toml
[[transport.jms.listener]]
name = "SQProxyCF"
parameter.initial_naming_factory = "com.sun.jndi.fscontext.RefFSContextFactory"
parameter.provider_url = "file:/C:/JNDI-Directory"
parameter.connection_factory_name = "MQ_JMS_MANAGER"
parameter.connection_factory_type = "queue"
parameter.destination = "JMS_QUEUE"

[[transport.jms.listener]]
name = "default"
parameter.initial_naming_factory = "com.sun.jndi.fscontext.RefFSContextFactory"
parameter.provider_url = "file:/C:/JNDI-Directory"
parameter.connection_factory_name = "MQ_JMS_MANAGER"
parameter.connection_factory_type = "queue"
parameter.destination = "JMS_QUEUE"
```

Queue Scenario 1: Client to Queue to WSO2 EI
10.
```toml
[[transport.jms.listener]]
name = "default"
parameter.initial_naming_factory = "com.sun.jndi.fscontext.RefFSContextFactory"
parameter.provider_url = "file:/C:/JNDI-Directory"
parameter.connection_factory_name = "MQ_JMS_MANAGER"
parameter.connection_factory_type = "queue"
parameter.destination = "JMS_QUEUE"
```

Queue Scenario 2: Client to WSO2 EI to Queue
1.
```toml
[[transport.jms.listener]]
name = "default"
parameter.initial_naming_factory = "com.sun.jndi.fscontext.RefFSContextFactory"
parameter.provider_url = "file:/C:/JNDI-Directory"
parameter.connection_factory_name = "MQ_JMS_MANAGER"
parameter.connection_factory_type = "queue"
parameter.destination = "JMS_QUEUE"
```

6.
```toml
[[transport.jms.listener]]
name = "SQProxyCF"
parameter.initial_naming_factory = "com.sun.jndi.fscontext.RefFSContextFactory"
parameter.provider_url = "file:/C:/JNDI-Directory"
parameter.connection_factory_name = "MQ_JMS_MANAGER"
parameter.connection_factory_type = "queue"
parameter.destination = "JMS_QUEUE"

[[transport.jms.listener]]
name = "default"
parameter.initial_naming_factory = "com.sun.jndi.fscontext.RefFSContextFactory"
parameter.provider_url = "file:/C:/JNDI-Directory"
parameter.connection_factory_name = "MQ_JMS_MANAGER"
parameter.connection_factory_type = "queue"
parameter.destination = "JMS_QUEUE"
```

Topic Scenario 1: Client to Topic to WSO2 EI
1.
```toml
[[transport.jms.listener]]
name = "myTopicConnectionFactory"
parameter.initial_naming_factory = "com.sun.jndi.fscontext.RefFSContextFactory"
parameter.provider_url = "file:/C:/JNDI-Directory"
parameter.connection_factory_name = "MQ_JMS_MANAGER"
parameter.connection_factory_type = "topic"
parameter.destination = "JMS_QUEUE"

[[transport.jms.listener]]
name = "default"
parameter.initial_naming_factory = "com.sun.jndi.fscontext.RefFSContextFactory"
parameter.provider_url = "file:/C:/JNDI-Directory"
parameter.connection_factory_name = "MQ_JMS_MANAGER"
parameter.connection_factory_type = "queue"
parameter.destination = "JMS_QUEUE"
```

9.
```toml
[[transport.jms.listener]]
name = "default"
parameter.initial_naming_factory = "com.sun.jndi.fscontext.RefFSContextFactory"
parameter.provider_url = "file:/C:/JNDI-Directory"
parameter.connection_factory_name = "MQ_JMS_MANAGER"
parameter.connection_factory_type = "queue"
parameter.destination = "bogusq"
```

Topic Scenario 2: Client to WSO2 EI to Topic¶
1.
```toml
[[transport.jms.listener]]
name = "default"
parameter.initial_naming_factory = "com.sun.jndi.fscontext.RefFSContextFactory"
parameter.provider_url = "file:/C:/JNDI-Directory"
parameter.connection_factory_name = "MQ_JMS_MANAGER"
parameter.connection_factory_type = "queue"
parameter.destination = "bogusq"
```

7.
```toml
[[transport.jms.listener]]
name = "myTopicConnectionFactory"
parameter.initial_naming_factory = "com.sun.jndi.fscontext.RefFSContextFactory"
parameter.provider_url = "file:/C:/JNDI-Directory"
parameter.connection_factory_name = "MQ_JMS_MANAGER"
parameter.connection_factory_type = "topic"
parameter.destination = "ivtT"

[[transport.jms.listener]]
name = "default"
parameter.initial_naming_factory = "com.sun.jndi.fscontext.RefFSContextFactory"
parameter.provider_url = "file:/C:/JNDI-Directory"
parameter.connection_factory_name = "MQ_JMS_MANAGER"
parameter.connection_factory_type = "queue"
parameter.destination = "bogusq"
```
