### ISSUE TITLE
Default carbon.properties system parameters cannot override by toml file

### ISSUE THREAD

**Issue by madushadhanushka** [wso2/docs-ei#916]
**Description:**
Following configuration in doc [https://ei.docs.wso2.com/en/latest/micro-integrator/develop/creating-artifacts/encrypting-synapse-passwords/#encrypting-passwords-for-synapse-configurations](https://ei.docs.wso2.com/en/latest/micro-integrator/develop/creating-artifacts/encrypting-synapse-passwords/#encrypting-passwords-for-synapse-configurations) could not be override by toml configuration.

```toml
[system.parameter]
'org.wso2.SecureVaultPasswordRegEx' = "^[\\\\S]{5,60}$"
```

Fixed with with PR https://github.com/wso2/micro-integrator/pull/1055
